dist: xenial
language: python
sudo: required
python: 3.7
cache: pip
before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -r requirements.txt
env:
  global:
    - CC_TEST_REPORTER_ID=3cbe2a1b8d277ba660268b94fa0aa1698e69d2b5a81aec7c6084d5bb45ff27dd
script:
  - python -m pytest --cov-config .coveragerc --cov=sample
  - rspec
after_script:
  - coverage xml
  - ./cc-test-reporter after-build
