dist: xenial
language: python
python: 3.7
cache: pip
addons:
    code_climate:
      repo_token: 3cbe2a1b8d277ba660268b94fa0aa1698e69d2b5a81aec7c6084d5bb45ff27dd

after_success:
  - bundle exec codeclimate-test-reporter
install:
  - pip install -r requirements.txt
script:
  - python -m pytest